export const initialDefaults = {
  Crop_Type: "Rice",
  SOC: "",
  N_Content: "",
  P_Content: "",
  K_Content: "",
  pH: "",
  Fertilizer_Type: "Urea",
  Fertilizer_Amount: "",
  Temperature: "",
  Rainfall: "",
  Humidity: "",
  Location: "",
  Latitude: 12.9716,
  Longitude: 77.5946,
  ReadableAddress: "Bengaluru, Karnataka, India",
  Village: "",
  Taluk: "",
  District: "",
  State: "",
  Country: "",
  PostalCode: "",
  selectedDistrict: "",
};

export const constraints = {
  SOC: { min: 0.5, max: 5.0, label: "Soil Organic Carbon" },
  N_Content: { min: 10, max: 200, label: "Nitrogen Content" },
  P_Content: { min: 5, max: 100, label: "Phosphorus Content" },
  K_Content: { min: 10, max: 150, label: "Potassium Content" },
  pH: { min: 4.5, max: 8.5, label: "pH Level" },
  Temperature: { min: 10, max: 38, label: "Temperature" },
  Rainfall: { min: 200, max: 2000, label: "Rainfall" },
  Humidity: { min: 30, max: 90, label: "Relative Humidity" },
  Fertilizer_Amount: { min: 0, max: 500, label: "Fertilizer Amount" },
};
